//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FooEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FooEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   BOMあり に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddBOM {
            get {
                return ResourceManager.GetString("AddBOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべてのファイル(*.*) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AllFileLable {
            get {
                return ResourceManager.GetString("AllFileLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmDialogCancelButton {
            get {
                return ResourceManager.GetString("ConfirmDialogCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存しない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmDialogNoSaveButton {
            get {
                return ResourceManager.GetString("ConfirmDialogNoSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmDialogSaveButton {
            get {
                return ResourceManager.GetString("ConfirmDialogSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更内容を保存しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmDocumentClose {
            get {
                return ResourceManager.GetString("ConfirmDocumentClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ＭＳ ゴシック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultTextBoxFontName {
            get {
                return ResourceManager.GetString("DefaultTextBoxFontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DocumetTypeNone {
            get {
                return ResourceManager.GetString("DocumetTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動判定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileDialogCheckBox {
            get {
                return ResourceManager.GetString("FileDialogCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileDialogCodepageLabel {
            get {
                return ResourceManager.GetString("FileDialogCodepageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   改行コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileDialogLineFeedLable {
            get {
                return ResourceManager.GetString("FileDialogLineFeedLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ドキュメントの終わりまで検索しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FindDialogNotFound {
            get {
                return ResourceManager.GetString("FindDialogNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FooEditor.chm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpFileName {
            get {
                return ResourceManager.GetString("HelpFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FooEditor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IPCServerName {
            get {
                return ResourceManager.GetString("IPCServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定した文字数で折り返す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LineBreakMethodCharCount {
            get {
                return ResourceManager.GetString("LineBreakMethodCharCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   折り返さない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LineBreakMethodNone {
            get {
                return ResourceManager.GetString("LineBreakMethodNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   右端で折り返す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LineBreakMethodPageBound {
            get {
                return ResourceManager.GetString("LineBreakMethodPageBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡大率:{0}% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MagnificationPowerFormat {
            get {
                return ResourceManager.GetString("MagnificationPowerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   矩形選択を使用不可能にしてください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MustBeDisableRectSelect {
            get {
                return ResourceManager.GetString("MustBeDisableRectSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無題{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewDocumentTitle {
            get {
                return ResourceManager.GetString("NewDocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FooEditorD100F6B6-4BB4-4D74-B6CF-57A7E3196A78 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessMutex {
            get {
                return ResourceManager.GetString("ProcessMutex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワークスペースを復元しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RecoveryConfirm {
            get {
                return ResourceManager.GetString("RecoveryConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FooEditorReovery{0}{1}.state に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RecoveryState {
            get {
                return ResourceManager.GetString("RecoveryState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全置換が完了しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReplaceAllComplete {
            get {
                return ResourceManager.GetString("ReplaceAllComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全ての文章モード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveForAllDocumentType {
            get {
                return ResourceManager.GetString("SaveForAllDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行:{0} 桁:{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextPointFormat {
            get {
                return ResourceManager.GetString("TextPointFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管理者でないと書き込みができないようです。昇格しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UACSaveConfirm {
            get {
                return ResourceManager.GetString("UACSaveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マイナスの値は入力できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VaildateErrorOnUnsignedNumber {
            get {
                return ResourceManager.GetString("VaildateErrorOnUnsignedNumber", resourceCulture);
            }
        }
    }
}
