//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringFilter.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StringFilter.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   スペースからタブに変換する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExpandSpaceMenuItem {
            get {
                return ResourceManager.GetString("ExpandSpaceMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タブをスペースに展開する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExpandTabMenuItem {
            get {
                return ResourceManager.GetString("ExpandTabMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   引用文にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InsertQuotationMenuItem {
            get {
                return ResourceManager.GetString("InsertQuotationMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インテンド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IntendMenuItem {
            get {
                return ResourceManager.GetString("IntendMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字列の操作 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StringFilterMenuItem {
            get {
                return ResourceManager.GetString("StringFilterMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実体参照に変更する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToEntityMenuItem {
            get {
                return ResourceManager.GetString("ToEntityMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全角に変換する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToFullWidthChar {
            get {
                return ResourceManager.GetString("ToFullWidthChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   半角に変換する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToHalfWidthChar {
            get {
                return ResourceManager.GetString("ToHalfWidthChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   小文字に変換する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToLowerMenuItem {
            get {
                return ResourceManager.GetString("ToLowerMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実体参照から復元する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToRealCharMenuItem {
            get {
                return ResourceManager.GetString("ToRealCharMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   大文字に変換する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToUpperMenuItem {
            get {
                return ResourceManager.GetString("ToUpperMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   逆インテンド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnIntendMenuItem {
            get {
                return ResourceManager.GetString("UnIntendMenuItem", resourceCulture);
            }
        }
    }
}
